# Package-level utilities loaded after all other files (zzz convention)

.onAttach <- function(libname, pkgname) {
  packageStartupMessage(
    "edinetsynth ", utils::packageVersion("edinetsynth"),
    " - Tidy tools for VilseckKI Synthetic EDINET Data\n",
    "  Datasets: https://jdex.jp (search: VilseckKI)\n",
    "  Package:  https://github.com/misawa-data-gk/edinetsynth"
  )
}


#' Citation Information for edinetsynth
#'
#' Prints a BibTeX citation for the edinetsynth package and the
#' VilseckKI EDINET dataset. Use in academic publications to
#' properly attribute the data source.
#'
#' @return Invisibly, a character vector of BibTeX entries.
#'
#' @examples
#' \dontrun{
#' edinetsynth_citation()
#' }
#'
#' @export
edinetsynth_citation <- function() {
  pkg_bib <- paste0(
    "@software{edinetsynth,\n",
    "  title = {edinetsynth: Tidy Tools for VilseckKI Synthetic EDINET Datasets},\n",
    "  author = {{ML Upskill Agents UG}},\n",
    "  year = {2026},\n",
    "  version = {", utils::packageVersion("edinetsynth"), "},\n",
    "  url = {https://github.com/misawa-data-gk/edinetsynth},\n",
    "  note = {R package}\n",
    "}\n"
  )

  data_bib <- paste0(
    "@misc{vilseckki_edinet_2026,\n",
    "  title = {Synthetic Japanese Securities Reports ({\\jpn{\u6709\u4fa1\u8a3c\u5238\u5831\u544a\u66f8}})},\n",
    "  author = {{VilseckKI / ML Upskill Agents UG}},\n",
    "  year = {2026},\n",
    "  howpublished = {JDEX (Japan Data Exchange)},\n",
    "  url = {https://jdex.jp},\n",
    "  note = {500 synthetic documents with quality-tiered error injection.\n",
    "          Generated by locally-run 70B LLM with FSA enforcement\n",
    "          flaw taxonomy. CC-BY-4.0 license.}\n",
    "}\n"
  )

  # Also mention DOI when available
  doi_note <- paste0(
    "% NOTE: Once a DOI is minted via Zenodo, add:\n",
    "%   doi = {10.5281/zenodo.XXXXXXX},\n",
    "% to the vilseckki_edinet_2026 entry.\n",
    "% Register at: https://zenodo.org/deposit/new\n"
  )

  full <- paste0(
    "# To cite edinetsynth in publications, use:\n\n",
    pkg_bib, "\n",
    data_bib, "\n",
    doi_note
  )

  cat(full)
  invisible(c(pkg_bib, data_bib))
}
